# Generated by Django 6.0.7 on 2026-08-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Restaurant Name')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('story', models.TextField(verbose_name='Story')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='Hero Image')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='About Image')),
                ('chef_name', models.CharField(blank=True, max_length=100, verbose_name='Chef Name')),
                ('chef_position', models.CharField(blank=True, max_length=120, verbose_name='Chef Position')),
                ('chef_bio', models.TextField(blank=True, verbose_name='Chef Biography')),
                ('chef_image', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='Chef Image')),
                ('experience_years', models.PositiveIntegerField(default=25, verbose_name='Years of Experience')),
                ('menu_items', models.PositiveIntegerField(default=120, verbose_name='Menu Items')),
                ('happy_customers', models.PositiveIntegerField(default=50000, verbose_name='Happy Customers')),
                ('awards', models.PositiveIntegerField(default=15, verbose_name='Awards')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurant',
            },
        ),
    ]
