# Generated by Django 6.0.7 on 2026-08-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='since',
            field=models.IntegerField(default=1998),
        ),
    ]
