# Generated by Django 6.0.7 on 2026-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(default='Monday - Sunday | 11:00 AM - 11:00 PM', max_length=100, verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='since',
            field=models.IntegerField(default=1998, verbose_name='Since'),
        ),
    ]
