# Generated by Django 6.0.7 on 2026-07-31 08:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'name'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Food Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Short Description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ingredients', models.TextField(blank=True, help_text='Separate ingredients with commas.', verbose_name='Ingredients')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in the selected currency.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='Food Image')),
                ('preparation_time', models.PositiveSmallIntegerField(default=15, verbose_name='Preparation Time (minutes)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
