# Generated by Django 6.0.7 on 2026-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('date', models.DateField(verbose_name='Reservation Date')),
                ('time', models.TimeField(verbose_name='Reservation Time')),
                ('guests', models.PositiveSmallIntegerField(verbose_name='Number of Guests')),
                ('message', models.TextField(blank=True, verbose_name='Additional Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('-date', '-time'),
            },
        ),
    ]
