# Generated by Django 6.0.7 on 2026-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='N/A', verbose_name='Delivery Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Order Notes'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
